/////////////////////////////////////////////////
//
// Automatically generated by the
// AddonGenerator script by Arya
//
/////////////////////////////////////////////////
using System;
using Server;
using Server.Items;
using Server.Engines.VeteranRewards;

namespace Server.Items
{
    public class ShowerSouthAddon : BaseAddon
	{
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ShowerSouthAddonDeed();
			}
		}

		[ Constructable ]
		public ShowerSouthAddon()
		{
			AddonComponent ac = null;
			ac = new AddonComponent( 13603 );
			AddComponent( ac, 0, 0, 0 );
			ac = new AddonComponent( 13603 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 13585 );
			AddComponent( ac, 0, -1, 2 );
			ac = new AddonComponent( 13585 );
			AddComponent( ac, -1, -1, 2 );
			ac = new AddonComponent( 6197 );
			AddComponent( ac, -1, -1, 15 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, 0, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, -1, 0 );
			ac = new AddonComponent( 6039 );
			AddComponent( ac, -1, 0, 0 );
			ac = new AddonComponent( 5645 );
			AddComponent( ac, 1, -1, 0 );
			ac = new AddonComponent( 5645 );
			AddComponent( ac, 1, 0, 0 );
			ac = new AddonComponent( 5645 );
			AddComponent( ac, 1, 1, 0 );
			ac = new AddonComponent( 5646 );
			AddComponent( ac, 0, 2, 0 );
			ac = new AddonComponent( 5646 );
			AddComponent( ac, -1, 2, 0 );

		}

		public ShowerSouthAddon( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

    public class ShowerSouthAddonDeed : BaseAddonDeed, IRewardItem
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ShowerSouthAddon();
			}
		}

        private bool m_IsRewardItem;

        [CommandProperty(AccessLevel.GameMaster)]
        public bool IsRewardItem
        {
            get { return m_IsRewardItem; }
            set { m_IsRewardItem = value; InvalidateProperties(); }
        }

		[Constructable]
		public ShowerSouthAddonDeed()
		{
			Name = "ShowerSouth";
		}

		public ShowerSouthAddonDeed( Serial serial ) : base( serial )
		{
		}
        public override void OnDoubleClick(Mobile from)
        {
            if (this.m_IsRewardItem && !RewardSystem.CheckIsUsableBy(from, this, null))
                return;

            base.OnDoubleClick(from);
        }
		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
            writer.Write((bool)this.m_IsRewardItem);
        }

        public override void Deserialize(GenericReader reader)
        {
            base.Deserialize(reader);

            int version = reader.ReadEncodedInt();

            this.m_IsRewardItem = reader.ReadBool(); ;
		}
	}
}